// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMMT2FbOaz56nZKDsaVwngzTJdtq9Uy8w',
    appId: '1:547370551904:android:b234216a7c80a35efe5105',
    messagingSenderId: '547370551904',
    projectId: 'mindfuck-886ec',
    databaseURL: 'https://mindfuck-886ec-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mindfuck-886ec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJ5RAjxKKaR-8_CIZEltwxy6Y-N_QPeN8',
    appId: '1:547370551904:ios:0231b929ba5b39a8fe5105',
    messagingSenderId: '547370551904',
    projectId: 'mindfuck-886ec',
    databaseURL: 'https://mindfuck-886ec-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mindfuck-886ec.firebasestorage.app',
    iosBundleId: 'com.example.mindfuck',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJ5RAjxKKaR-8_CIZEltwxy6Y-N_QPeN8',
    appId: '1:547370551904:ios:0231b929ba5b39a8fe5105',
    messagingSenderId: '547370551904',
    projectId: 'mindfuck-886ec',
    databaseURL: 'https://mindfuck-886ec-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mindfuck-886ec.firebasestorage.app',
    iosBundleId: 'com.example.mindfuck',
  );
}
